// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: command_import_errors.sql

package store

import (
	"context"
)

const clearImportErrors = `-- name: ClearImportErrors :exec
DELETE FROM command_import_errors
`

func (q *Queries) ClearImportErrors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearImportErrors)
	return err
}

const deleteImportError = `-- name: DeleteImportError :exec
DELETE FROM command_import_errors WHERE filename = $1
`

func (q *Queries) DeleteImportError(ctx context.Context, filename string) error {
	_, err := q.db.Exec(ctx, deleteImportError, filename)
	return err
}

const listImportErrors = `-- name: ListImportErrors :many
SELECT filename, error, failed_at
FROM command_import_errors
ORDER BY filename
`

func (q *Queries) ListImportErrors(ctx context.Context) ([]CommandImportError, error) {
	rows, err := q.db.Query(ctx, listImportErrors)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandImportError{}
	for rows.Next() {
		var i CommandImportError
		if err := rows.Scan(&i.Filename, &i.Error, &i.FailedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertImportError = `-- name: UpsertImportError :exec
INSERT INTO command_import_errors (filename, error, failed_at)
VALUES ($1, $2, NOW())
ON CONFLICT (filename) DO UPDATE
    SET error     = EXCLUDED.error,
        failed_at = EXCLUDED.failed_at
`

type UpsertImportErrorParams struct {
	Filename string `json:"filename"`
	Error    string `json:"error"`
}

func (q *Queries) UpsertImportError(ctx context.Context, arg UpsertImportErrorParams) error {
	_, err := q.db.Exec(ctx, upsertImportError, arg.Filename, arg.Error)
	return err
}
