// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: commands.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const deactivateCommand = `-- name: DeactivateCommand :exec
UPDATE commands SET is_active = false WHERE slug = $1
`

func (q *Queries) DeactivateCommand(ctx context.Context, slug string) error {
	_, err := q.db.Exec(ctx, deactivateCommand, slug)
	return err
}

const getCommandByID = `-- name: GetCommandByID :one
SELECT id, slug, name, description, script_path, is_active, registered_at FROM commands WHERE id = $1
`

func (q *Queries) GetCommandByID(ctx context.Context, id uuid.UUID) (Command, error) {
	row := q.db.QueryRow(ctx, getCommandByID, id)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ScriptPath,
		&i.IsActive,
		&i.RegisteredAt,
	)
	return i, err
}

const getCommandBySlug = `-- name: GetCommandBySlug :one
SELECT id, slug, name, description, script_path, is_active, registered_at FROM commands WHERE slug = $1 AND is_active = true
`

func (q *Queries) GetCommandBySlug(ctx context.Context, slug string) (Command, error) {
	row := q.db.QueryRow(ctx, getCommandBySlug, slug)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ScriptPath,
		&i.IsActive,
		&i.RegisteredAt,
	)
	return i, err
}

const listAllCommands = `-- name: ListAllCommands :many
SELECT id, slug, name, description, script_path, is_active, registered_at FROM commands WHERE is_active = true ORDER BY name
`

func (q *Queries) ListAllCommands(ctx context.Context) ([]Command, error) {
	rows, err := q.db.Query(ctx, listAllCommands)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ScriptPath,
			&i.IsActive,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCommandsForUser = `-- name: ListCommandsForUser :many
SELECT DISTINCT c.id, c.slug, c.name, c.description, c.script_path, c.is_active, c.registered_at FROM commands c
LEFT JOIN command_permissions cp ON cp.command_id = c.id
LEFT JOIN user_group_members ugm ON ugm.user_id = $1 AND ugm.group_id = cp.grantee_id
WHERE c.is_active = true
  AND (
      cp.grantee_type = 'user' AND cp.grantee_id = $1
   OR cp.grantee_type = 'group' AND ugm.user_id = $1
  )
ORDER BY c.name
`

func (q *Queries) ListCommandsForUser(ctx context.Context, userID uuid.UUID) ([]Command, error) {
	rows, err := q.db.Query(ctx, listCommandsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Command{}
	for rows.Next() {
		var i Command
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Description,
			&i.ScriptPath,
			&i.IsActive,
			&i.RegisteredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCommand = `-- name: UpsertCommand :one
INSERT INTO commands (slug, name, description, script_path)
VALUES ($1, $2, $3, $4)
ON CONFLICT (slug) DO UPDATE
    SET name        = EXCLUDED.name,
        description = EXCLUDED.description,
        script_path = EXCLUDED.script_path,
        is_active   = true
RETURNING id, slug, name, description, script_path, is_active, registered_at
`

type UpsertCommandParams struct {
	Slug        string `json:"slug"`
	Name        string `json:"name"`
	Description string `json:"description"`
	ScriptPath  string `json:"script_path"`
}

func (q *Queries) UpsertCommand(ctx context.Context, arg UpsertCommandParams) (Command, error) {
	row := q.db.QueryRow(ctx, upsertCommand,
		arg.Slug,
		arg.Name,
		arg.Description,
		arg.ScriptPath,
	)
	var i Command
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Description,
		&i.ScriptPath,
		&i.IsActive,
		&i.RegisteredAt,
	)
	return i, err
}
