// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: command_inputs.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCommandInput = `-- name: CreateCommandInput :one
INSERT INTO command_inputs (command_id, name, label, type, options, multi, required, sort_order)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, command_id, name, label, type, options, multi, required, sort_order
`

type CreateCommandInputParams struct {
	CommandID uuid.UUID `json:"command_id"`
	Name      string    `json:"name"`
	Label     string    `json:"label"`
	Type      string    `json:"type"`
	Options   []byte    `json:"options"`
	Multi     bool      `json:"multi"`
	Required  bool      `json:"required"`
	SortOrder int32     `json:"sort_order"`
}

func (q *Queries) CreateCommandInput(ctx context.Context, arg CreateCommandInputParams) (CommandInput, error) {
	row := q.db.QueryRow(ctx, createCommandInput,
		arg.CommandID,
		arg.Name,
		arg.Label,
		arg.Type,
		arg.Options,
		arg.Multi,
		arg.Required,
		arg.SortOrder,
	)
	var i CommandInput
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.Name,
		&i.Label,
		&i.Type,
		&i.Options,
		&i.Multi,
		&i.Required,
		&i.SortOrder,
	)
	return i, err
}

const deleteCommandInputs = `-- name: DeleteCommandInputs :exec
DELETE FROM command_inputs WHERE command_id = $1
`

func (q *Queries) DeleteCommandInputs(ctx context.Context, commandID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCommandInputs, commandID)
	return err
}

const listCommandInputs = `-- name: ListCommandInputs :many
SELECT id, command_id, name, label, type, options, multi, required, sort_order FROM command_inputs
WHERE command_id = $1
ORDER BY sort_order, name
`

func (q *Queries) ListCommandInputs(ctx context.Context, commandID uuid.UUID) ([]CommandInput, error) {
	rows, err := q.db.Query(ctx, listCommandInputs, commandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandInput{}
	for rows.Next() {
		var i CommandInput
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.Name,
			&i.Label,
			&i.Type,
			&i.Options,
			&i.Multi,
			&i.Required,
			&i.SortOrder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
