// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: command_permissions.sql

package store

import (
	"context"

	"github.com/google/uuid"
)

const createCommandPermission = `-- name: CreateCommandPermission :one
INSERT INTO command_permissions (command_id, grantee_type, grantee_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
RETURNING id, command_id, grantee_type, grantee_id
`

type CreateCommandPermissionParams struct {
	CommandID   uuid.UUID `json:"command_id"`
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) CreateCommandPermission(ctx context.Context, arg CreateCommandPermissionParams) (CommandPermission, error) {
	row := q.db.QueryRow(ctx, createCommandPermission, arg.CommandID, arg.GranteeType, arg.GranteeID)
	var i CommandPermission
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.GranteeType,
		&i.GranteeID,
	)
	return i, err
}

const deleteAllCommandPermissions = `-- name: DeleteAllCommandPermissions :exec
DELETE FROM command_permissions WHERE command_id = $1
`

func (q *Queries) DeleteAllCommandPermissions(ctx context.Context, commandID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllCommandPermissions, commandID)
	return err
}

const deleteCommandPermission = `-- name: DeleteCommandPermission :exec
DELETE FROM command_permissions
WHERE command_id = $1 AND grantee_type = $2 AND grantee_id = $3
`

type DeleteCommandPermissionParams struct {
	CommandID   uuid.UUID `json:"command_id"`
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

func (q *Queries) DeleteCommandPermission(ctx context.Context, arg DeleteCommandPermissionParams) error {
	_, err := q.db.Exec(ctx, deleteCommandPermission, arg.CommandID, arg.GranteeType, arg.GranteeID)
	return err
}

const listCommandPermissions = `-- name: ListCommandPermissions :many
SELECT id, command_id, grantee_type, grantee_id FROM command_permissions WHERE command_id = $1
`

func (q *Queries) ListCommandPermissions(ctx context.Context, commandID uuid.UUID) ([]CommandPermission, error) {
	rows, err := q.db.Query(ctx, listCommandPermissions, commandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CommandPermission{}
	for rows.Next() {
		var i CommandPermission
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.GranteeType,
			&i.GranteeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const userCanAccessCommand = `-- name: UserCanAccessCommand :one
SELECT EXISTS (
    SELECT 1 FROM command_permissions cp
    LEFT JOIN user_group_members ugm
           ON ugm.user_id = $1 AND ugm.group_id = cp.grantee_id
    WHERE cp.command_id = $2
      AND (
          (cp.grantee_type = 'user'  AND cp.grantee_id = $1)
       OR (cp.grantee_type = 'group' AND ugm.user_id   IS NOT NULL)
      )
) AS has_access
`

type UserCanAccessCommandParams struct {
	UserID    uuid.UUID `json:"user_id"`
	CommandID uuid.UUID `json:"command_id"`
}

func (q *Queries) UserCanAccessCommand(ctx context.Context, arg UserCanAccessCommandParams) (bool, error) {
	row := q.db.QueryRow(ctx, userCanAccessCommand, arg.UserID, arg.CommandID)
	var has_access bool
	err := row.Scan(&has_access)
	return has_access, err
}
