// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config_entries.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createConfigEntry = `-- name: CreateConfigEntry :one
INSERT INTO config_entries (key, value_encrypted, description, created_by)
VALUES ($1, $2, $3, $4)
RETURNING id, key, value_encrypted, description, created_by, created_at, updated_at
`

type CreateConfigEntryParams struct {
	Key            string    `json:"key"`
	ValueEncrypted []byte    `json:"value_encrypted"`
	Description    string    `json:"description"`
	CreatedBy      uuid.UUID `json:"created_by"`
}

func (q *Queries) CreateConfigEntry(ctx context.Context, arg CreateConfigEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, createConfigEntry,
		arg.Key,
		arg.ValueEncrypted,
		arg.Description,
		arg.CreatedBy,
	)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ValueEncrypted,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConfigEntry = `-- name: DeleteConfigEntry :exec
DELETE FROM config_entries WHERE key = $1
`

func (q *Queries) DeleteConfigEntry(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, deleteConfigEntry, key)
	return err
}

const getConfigEntryByKey = `-- name: GetConfigEntryByKey :one
SELECT id, key, value_encrypted, description, created_by, created_at, updated_at FROM config_entries WHERE key = $1
`

func (q *Queries) GetConfigEntryByKey(ctx context.Context, key string) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, getConfigEntryByKey, key)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ValueEncrypted,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigEntries = `-- name: ListConfigEntries :many
SELECT id, key, description, created_by, created_at, updated_at
FROM config_entries
ORDER BY key
`

type ListConfigEntriesRow struct {
	ID          uuid.UUID          `json:"id"`
	Key         string             `json:"key"`
	Description string             `json:"description"`
	CreatedBy   uuid.UUID          `json:"created_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListConfigEntries(ctx context.Context) ([]ListConfigEntriesRow, error) {
	rows, err := q.db.Query(ctx, listConfigEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConfigEntriesRow{}
	for rows.Next() {
		var i ListConfigEntriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Key,
			&i.Description,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfigEntry = `-- name: UpdateConfigEntry :one
UPDATE config_entries
SET value_encrypted = $2, description = $3, updated_at = NOW()
WHERE key = $1
RETURNING id, key, value_encrypted, description, created_by, created_at, updated_at
`

type UpdateConfigEntryParams struct {
	Key            string `json:"key"`
	ValueEncrypted []byte `json:"value_encrypted"`
	Description    string `json:"description"`
}

func (q *Queries) UpdateConfigEntry(ctx context.Context, arg UpdateConfigEntryParams) (ConfigEntry, error) {
	row := q.db.QueryRow(ctx, updateConfigEntry, arg.Key, arg.ValueEncrypted, arg.Description)
	var i ConfigEntry
	err := row.Scan(
		&i.ID,
		&i.Key,
		&i.ValueEncrypted,
		&i.Description,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
