// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package store

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (command_id, triggered_by, inputs)
VALUES ($1, $2, $3)
RETURNING id, command_id, triggered_by, inputs, status, error_message, started_at, completed_at, created_at
`

type CreateExecutionParams struct {
	CommandID   uuid.UUID `json:"command_id"`
	TriggeredBy uuid.UUID `json:"triggered_by"`
	Inputs      []byte    `json:"inputs"`
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution, arg.CommandID, arg.TriggeredBy, arg.Inputs)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.TriggeredBy,
		&i.Inputs,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT id, command_id, triggered_by, inputs, status, error_message, started_at, completed_at, created_at FROM executions WHERE id = $1
`

func (q *Queries) GetExecutionByID(ctx context.Context, id uuid.UUID) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, id)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.TriggeredBy,
		&i.Inputs,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExecutionsForCommand = `-- name: ListExecutionsForCommand :many
SELECT e.id, e.command_id, e.triggered_by, e.inputs, e.status, e.error_message, e.started_at, e.completed_at, e.created_at, u.name AS triggered_by_name, u.email AS triggered_by_email
FROM executions e
JOIN users u ON u.id = e.triggered_by
WHERE e.command_id = $1
ORDER BY e.created_at DESC
LIMIT $2
`

type ListExecutionsForCommandParams struct {
	CommandID uuid.UUID `json:"command_id"`
	Limit     int32     `json:"limit"`
}

type ListExecutionsForCommandRow struct {
	ID               uuid.UUID          `json:"id"`
	CommandID        uuid.UUID          `json:"command_id"`
	TriggeredBy      uuid.UUID          `json:"triggered_by"`
	Inputs           []byte             `json:"inputs"`
	Status           string             `json:"status"`
	ErrorMessage     string             `json:"error_message"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	CompletedAt      pgtype.Timestamptz `json:"completed_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	TriggeredByName  string             `json:"triggered_by_name"`
	TriggeredByEmail string             `json:"triggered_by_email"`
}

func (q *Queries) ListExecutionsForCommand(ctx context.Context, arg ListExecutionsForCommandParams) ([]ListExecutionsForCommandRow, error) {
	rows, err := q.db.Query(ctx, listExecutionsForCommand, arg.CommandID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExecutionsForCommandRow{}
	for rows.Next() {
		var i ListExecutionsForCommandRow
		if err := rows.Scan(
			&i.ID,
			&i.CommandID,
			&i.TriggeredBy,
			&i.Inputs,
			&i.Status,
			&i.ErrorMessage,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.TriggeredByName,
			&i.TriggeredByEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE executions
SET status        = $2,
    error_message = $3,
    started_at    = $4,
    completed_at  = $5
WHERE id = $1
RETURNING id, command_id, triggered_by, inputs, status, error_message, started_at, completed_at, created_at
`

type UpdateExecutionStatusParams struct {
	ID           uuid.UUID          `json:"id"`
	Status       string             `json:"status"`
	ErrorMessage string             `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatus,
		arg.ID,
		arg.Status,
		arg.ErrorMessage,
		arg.StartedAt,
		arg.CompletedAt,
	)
	var i Execution
	err := row.Scan(
		&i.ID,
		&i.CommandID,
		&i.TriggeredBy,
		&i.Inputs,
		&i.Status,
		&i.ErrorMessage,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}
