// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package store

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Command struct {
	ID           uuid.UUID          `json:"id"`
	Slug         string             `json:"slug"`
	Name         string             `json:"name"`
	Description  string             `json:"description"`
	ScriptPath   string             `json:"script_path"`
	IsActive     bool               `json:"is_active"`
	RegisteredAt pgtype.Timestamptz `json:"registered_at"`
}

type CommandImportError struct {
	Filename string             `json:"filename"`
	Error    string             `json:"error"`
	FailedAt pgtype.Timestamptz `json:"failed_at"`
}

type CommandInput struct {
	ID        uuid.UUID `json:"id"`
	CommandID uuid.UUID `json:"command_id"`
	Name      string    `json:"name"`
	Label     string    `json:"label"`
	Type      string    `json:"type"`
	Options   []byte    `json:"options"`
	Multi     bool      `json:"multi"`
	Required  bool      `json:"required"`
	SortOrder int32     `json:"sort_order"`
}

type CommandPermission struct {
	ID          uuid.UUID `json:"id"`
	CommandID   uuid.UUID `json:"command_id"`
	GranteeType string    `json:"grantee_type"`
	GranteeID   uuid.UUID `json:"grantee_id"`
}

type ConfigEntry struct {
	ID             uuid.UUID          `json:"id"`
	Key            string             `json:"key"`
	ValueEncrypted []byte             `json:"value_encrypted"`
	Description    string             `json:"description"`
	CreatedBy      uuid.UUID          `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Execution struct {
	ID           uuid.UUID          `json:"id"`
	CommandID    uuid.UUID          `json:"command_id"`
	TriggeredBy  uuid.UUID          `json:"triggered_by"`
	Inputs       []byte             `json:"inputs"`
	Status       string             `json:"status"`
	ErrorMessage string             `json:"error_message"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type Group struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	IsActive  bool               `json:"is_active"`
}

type User struct {
	ID           uuid.UUID          `json:"id"`
	Email        string             `json:"email"`
	Name         string             `json:"name"`
	PasswordHash string             `json:"password_hash"`
	IsAdmin      bool               `json:"is_admin"`
	IsActive     bool               `json:"is_active"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type UserGroupMember struct {
	UserID  uuid.UUID `json:"user_id"`
	GroupID uuid.UUID `json:"group_id"`
}
